### ISSUE TITLE
Examples do not render as shown

### ISSUE THREAD

**Issue by sheki** [uber-common/react-vis#31]
I tried out the example provided at https://github.com/uber-common/react-vis/blob/master/src/example/plot/line-chart.js

It renders as https://i.imgur.com/efmrQBg.png when I try it out.
Does any one know whats up ?

**Comment by chrisirhc** [comment]
You might be missing the styles. Did you include the main.scss ?
We need to make that clearer in the documentation

**Comment by bulyonov** [comment]
@chrisirhc , @sheki , will add the necessary stuff into the docs.

**Comment by sheki** [comment]
Thanks

**Comment by bulyonov** [comment]
I'm closing this task since the changes were made in docs.

> Include the CSS from ./node_modules/react-vis/main in your HTML page or via SASS: `@import "./node_modules/react-vis/main";`
