### ISSUE TITLE
Y axis issues when data is constant

### ISSUE THREAD

**Issue by jamesfzhang** [uber-common/react-vis#36]
The y-axis lacks a tickmark when data is constant. I'd expect the line series to be vertically in the xyplot with 1 tickmark & gridline at the value specified.

```jsx
<XYPlot
  width={600}
  height={300}>
  <HorizontalGridLines />
  <LineMarkSeries
    color='blue'
    data={[ {x: 1,y:10}, {x: 2, y:10}]}/>
  <XAxis />
  <YAxis />
</XYPlot>
```
<img width="589" alt="screen shot 2016-03-17 at 3 35 39 pm" src="https://cloud.githubusercontent.com/assets/2057670/13863274/f56d4df8-ec55-11e5-88b0-92082fcdb133.png">

**Comment by bulyonov** [comment]
This issue has the same source as #40. The pull request for that is waiting for the review.

For now I'm closing this issue as duplicate.
