### ISSUE TITLE
Add Labels in Scatter/Bubble Plot

### ISSUE THREAD

**Issue by baileyid** [uber-common/react-vis#43]
Label field on bubble chart - now you can make cool bubble charts, but you are not able to understand what this specific bubble stands for without clicking on it

**Comment by chrisirhc** [comment]
@baileyid do you have a design in mind or perhaps some suggested screenshots? There are many kinds of labels. Are you referring to axis labels?

**Comment by baileyid** [comment]
I think the original request is asking for something like this:
![image](https://cloud.githubusercontent.com/assets/8864469/14267550/45910142-fa86-11e5-9599-f366a1942ef8.png)

There could be another dimension to label the points in bubble chart

**Comment by chrisirhc** [comment]
Interesting, this should be possible by adding a Hint for each mark?

**Comment by baileyid** [comment]
Cool! I didn't know we could display customized values in Hints before. I think this should do that. Thanks!
