### ISSUE TITLE
getStackedData causes an error if XY-Plot maps data into series children

### ISSUE THREAD

**Issue by akam9865** [uber-common/react-vis#47]
`var data = child.props.data;` on line 109 of `series-utils.js` will fail if the XY-Plot maps data into children such as this case: 
```
{dataSets.map((set, index) => {
  return (
    <LineSeries
      key={index}
      data={set.points}
      onNearestX={this.onNearestX.bind(null, set.name)}
      color={colorMap[set.name]} />
  );
})}
```
which will send an array of children to the `getStackedData` function, and `child.props` will be undefined, causing this error: `Uncaught TypeError: Cannot read property 'data' of undefined`

**Comment by chrisirhc** [comment]
I'm not sure I understand you, which version of the code are you looking at? I couldn't find `var data = child.props.data` in https://github.com/uber-common/react-vis/blob/add769142b65300ae37fc620e5b440c6c6191743/src/lib/utils/series-utils.js .

Could you write a fuller example with example data? [A good example](https://en.wikipedia.org/wiki/Minimal_Working_Example) is one that's minimal and demonstrates the bug.

**Comment by chrisirhc** [comment]
Oh I see you're referring to compile code probably of at the following line https://github.com/uber-common/react-vis/blob/add769142b65300ae37fc620e5b440c6c6191743/src/lib/utils/series-utils.js#L76 . However, how would the array be sent to getStackedData, isn't this function being applied to each child ([in this forEach](https://github.com/uber-common/react-vis/blob/add769142b65300ae37fc620e5b440c6c6191743/src/lib/utils/series-utils.js#L71))?

**Comment by bulyonov** [comment]
@akam9865 , could you confirm if you still have this issue?

**Comment by bulyonov** [comment]
I accidentally found a source of issue. It is the same as #54 .
I'm closing this task as a duplicate since the other one has an example for that.
